export default seed = [
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "client",
    createdAt: new Date(),
  },
  {
    type: "info",
    body: "INFO – the standard log level indicating that something happened, the application entered a certain state, etc",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "verbose",
    body: "involves more information than the standard or typical logging process",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "error",
    body: "error log is a record of critical errors that are encountered by the application, operating system or server while in operation.",
    source: "server",
    createdAt: new Date(),
  },
  {
    type: "warning",
    body: "Anything that can potentially cause application oddities, but for which I am automatically recovering",
    source: "server",
    createdAt: new Date(),
  },
];
